import { defineStore } from 'pinia'

export const useUserStore = defineStore('user', {
  state: () => ({
    users: [
      { id: '101', firstName: 'آرمین' },
      { id: '102', firstName: 'پویا' },
      { id: '103', firstName: 'محمد' },
      { id: '104', firstName: 'سامان' },
      { id: '105', firstName: 'علی' },
      { id: '106', firstName: 'حسین' },
      { id: '107', firstName: 'رضا' },
      { id: '108', firstName: 'امیر' },
      { id: '109', firstName: 'میلاد' },
      { id: '110', firstName: 'بابک' },
      { id: '111', firstName: 'سجاد' },
      { id: '112', firstName: 'مازیار' },
      { id: '113', firstName: 'مهرداد' },
      { id: '114', firstName: 'پیمان' },
      { id: '115', firstName: 'فرزاد' },
      { id: '116', firstName: 'محمود' },
      { id: '117', firstName: 'احسان' },
      { id: '118', firstName: 'کیانوش' },
      { id: '119', firstName: 'سعید' },
      { id: '120', firstName: 'بهروز' },
      { id: '121', firstName: 'محسن' },
      { id: '122', firstName: 'رامین' },
      { id: '123', firstName: 'بهراد' },
      { id: '124', firstName: 'آرش' },
      { id: '125', firstName: 'محمدرضا' },
      { id: '126', firstName: 'محمدامین' },
      { id: '127', firstName: 'علیرضا' },
      { id: '128', firstName: 'سپهر' },
      // { id: '129', firstName: 'مهدی' },
      // { id: '130', firstName: 'امید' },
      // { id: '131', firstName: 'فرهاد' },
      // { id: '132', firstName: 'پارسا' },
      // { id: '133', firstName: 'مصطفی' },
      // { id: '134', firstName: 'مهران' },
      // { id: '135', firstName: 'بهزاد' },
      // { id: '136', firstName: 'رهام' },
      // { id: '137', firstName: 'حامد' },
      // { id: '138', firstName: 'احمد' },
      // { id: '139', firstName: 'میثم' },
      // { id: '140', firstName: 'شایان' },
      // { id: '141', firstName: 'شهاب' },
      // { id: '142', firstName: 'فریدون' },
      // { id: '143', firstName: 'امین' },
      // { id: '144', firstName: 'پارمیدا' },
      // { id: '145', firstName: 'آرمان' },
      // { id: '146', firstName: 'محمدجواد' },
      // { id: '147', firstName: 'بهمن' },
      // { id: '148', firstName: 'عرفان' },
      // { id: '149', firstName: 'مهراب' },
      // { id: '150', firstName: 'سامر' },
      // { id: '151', firstName: 'سیاوش' },
      // { id: '152', firstName: 'شروین' },
      // { id: '153', firstName: 'محمدحسین' },
      // { id: '154', firstName: 'بهنام' },
      // { id: '155', firstName: 'پویان' },
      // { id: '156', firstName: 'امیرحسین' },
      // { id: '157', firstName: 'سیامک' },
      // { id: '158', firstName: 'محمدمهدی' },
      // { id: '159', firstName: 'شایان' },
      { id: '160', firstName: 'مجید' }
    ]
  }),
  getters: {},
  actions: {}
})
